In [1]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [2]:
# load movie databases and merge in pandas
movie_file = pd.read_csv('movies.csv')
ratings_file = pd.read_csv('ratings.csv')
df = pd.merge(movie_file, ratings_file)
df

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483
5,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18,3.5,1455209816
6,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19,4.0,965705637
7,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,21,3.5,1407618878
8,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,27,3.0,962685262
9,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,31,5.0,850466616
10,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,32,3.0,856736119
11,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,33,3.0,939647444
12,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,40,5.0,832058959
13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,43,5.0,848993983
14,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,44,3.0,869251860
15,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,45,4.0,951170182
16,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,46,5.0,834787906
17,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,50,3.0,1514238116
18,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,54,3.0,830247330
19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,57,5.0,965796031
20,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,63,5.0,1443199669
21,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,64,4.0,1161520134
22,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,66,4.0,1104643957
23,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,68,2.5,1158531426
24,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,71,5.0,864737933
25,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,73,4.5,1464196374
26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,76,0.5,1439165548
27,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,78,4.0,1252575124
28,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,82,2.5,1084467729
29,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,86,4.0,1344082549
...,...,...,...,...,...,...
100806,188301,Ant-Man and the Wasp (2018),Action|Adventure|Comedy|Fantasy|Sci-Fi,596,4.0,1535709468
100807,188675,Dogman (2018),Crime|Drama,318,3.5,1535035470
100808,188751,Mamma Mia: Here We Go Again! (2018),Comedy|Romance,212,4.5,1532362151
100809,188797,Tag (2018),Comedy,514,4.0,1535941279
100810,188833,The Man Who Killed Don Quixote (2018),Adventure|Comedy|Fantasy,318,4.5,1535035971
100811,189043,Boundaries (2018),Comedy|Drama,338,2.5,1530148447
100812,189111,Spiral (2018),Documentary,338,3.0,1530148343
100813,189333,Mission: Impossible - Fallout (2018),Action|Adventure|Thriller,184,4.0,1537110051
100814,189333,Mission: Impossible - Fallout (2018),Action|Adventure|Thriller,248,3.5,1534602181
100815,189381,SuperFly (2018),Action|Crime|Thriller,318,2.5,1536097988
100816,189547,Iron Soldier (2010),Action|Sci-Fi,210,1.0,1528486011
100817,189713,BlacKkKlansman (2018),Comedy|Crime|Drama,462,2.5,1536467299
100818,190183,The Darkest Minds (2018),Sci-Fi|Thriller,50,3.5,1533302021
100819,190207,Tilt (2011),Drama|Romance,338,1.5,1530148481
100820,190209,Jeff Ross Roasts the Border (2017),Comedy,338,4.0,1530148487
100821,190213,John From (2015),Drama,338,1.0,1530148478
100822,190215,Liquid Truth (2017),Drama,338,1.5,1530148477
100823,190219,Bunny (1998),Animation,338,1.0,1530148473
100824,190221,Hommage à Zgougou (et salut à Sabine Mamou) (2...,Documentary,338,1.0,1530148473
100825,191005,Gintama (2017),Action|Adventure|Comedy|Sci-Fi,184,4.5,1537109489
100826,193565,Gintama: The Movie (2010),Action|Animation|Comedy|Sci-Fi,184,3.5,1537098554
100827,193567,anohana: The Flower We Saw That Day - The Movi...,Animation|Drama,184,3.0,1537099103
100828,193571,Silver Spoon (2014),Comedy|Drama,184,4.0,1537099392
100829,193573,Love Live! The School Idol Movie (2015),Animation,184,4.0,1537099811
100830,193579,Jon Stewart Has Left the Building (2015),Documentary,184,3.5,1537107259
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,1537109082
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,1537109545
100833,193585,Flint (2017),Drama,184,3.5,1537109805
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,1537110021
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,1537157606

In [3]:
# pivot table
ratings = pd.pivot_table(df, index='userId', columns='title', values='rating')
ratings.head(3)

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
ratings = ratings.reindex(ratings.count().sort_values(ascending=False).index, axis=1)
ratings.head(3)

title,Forrest Gump (1994),"Shawshank Redemption, The (1994)",Pulp Fiction (1994),"Silence of the Lambs, The (1991)","Matrix, The (1999)",Star Wars: Episode IV - A New Hope (1977),Jurassic Park (1993),Braveheart (1995),Terminator 2: Judgment Day (1991),Schindler's List (1993),...,"Last Wedding, The (Kivenpyörittäjän kylä) (1995)","Last Winter, The (2006)",Last Year's Snow Was Falling (1983),Last of the Dogmen (1995),Late Marriage (Hatuna Meuheret) (2001),Late Night Shopping (2001),Late Night with Conan O'Brien: The Best of Triumph the Insult Comic Dog (2004),"Late Shift, The (1996)",Latter Days (2003),'71 (2014)
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,3.0,4.0,5.0,5.0,4.0,4.0,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
ratings_full = ratings.fillna(0) #fill the NaN with the mean of each column
ratings_full.head(3)

title,Forrest Gump (1994),"Shawshank Redemption, The (1994)",Pulp Fiction (1994),"Silence of the Lambs, The (1991)","Matrix, The (1999)",Star Wars: Episode IV - A New Hope (1977),Jurassic Park (1993),Braveheart (1995),Terminator 2: Judgment Day (1991),Schindler's List (1993),...,"Last Wedding, The (Kivenpyörittäjän kylä) (1995)","Last Winter, The (2006)",Last Year's Snow Was Falling (1983),Last of the Dogmen (1995),Late Marriage (Hatuna Meuheret) (2001),Late Night Shopping (2001),Late Night with Conan O'Brien: The Best of Triumph the Insult Comic Dog (2004),"Late Shift, The (1996)",Latter Days (2003),'71 (2014)
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,3.0,4.0,5.0,5.0,4.0,4.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
#finding correlations using corrwith

correlation = ratings_full.corrwith(ratings_full['Forrest Gump (1994)'], axis=0, drop=False)
correlation.head(5)  #first five results in the data frame

title
Forrest Gump (1994)                 1.000000
Shawshank Redemption, The (1994)    0.411180
Pulp Fiction (1994)                 0.373776
Silence of the Lambs, The (1991)    0.312303
Matrix, The (1999)                  0.260824
dtype: float64

In [7]:
correlation.sort_values(ascending = False).head(10)  # the top ten most correlated movies in the dataframe

title
Forrest Gump (1994)                 1.000000
Jurassic Park (1993)                0.453632
Mrs. Doubtfire (1993)               0.440460
Shawshank Redemption, The (1994)    0.411180
Apollo 13 (1995)                    0.390374
Pretty Woman (1990)                 0.390179
Braveheart (1995)                   0.374274
Pulp Fiction (1994)                 0.373776
Lion King, The (1994)               0.358141
Speed (1994)                        0.348109
dtype: float64